CREATE TABLE `EMPLOYEES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(2000) NOT NULL,
  `LAST_NAME` varchar(2000) NOT NULL,
  `DOB` date NOT NULL,
  `GENDER` char(1) NOT NULL DEFAULT 'F',
  `DOJ` date NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15007 DEFAULT CHARSET=latin1;
